using SatisfactoryTree.Models;

namespace SatisfactoryTree.Helpers
{
    public class AllItemGroups
    {
        List<ItemGroup> ItemGroups { get; set; }
        public AllItemGroups()
        {
            List<ItemGroup> itemGroups = new()
            {
                new(0,"Tier 0", 0 ),
                new(0,"Iron Ore", 1),
                new(0,"Copper Ore", 1),
                new(0,"Limestone", 1),
                new(0,"Alien Protein", 1),
                new(0,"Leaves", 1),
                new(0,"Mycelia", 1),
                new(0,"Wood", 1),
                new(0,"Coal", 3),
                new(0,"Water", 3),
                new(0,"Crude Oil", 5),
                new(0,"Caterium Ore", 6),
                new(0,"Bauxite", 7),
                new(0,"Raw Quartz", 7),
                new(0,"Sulfur", 7),
                new(0,"Uranium", 8),
                new(0,"NitrogenGas", 8),
                new(1,"Iron Ingot", 1),
                new(1,"Copper Ingot", 1),
                new(1,"Concrete", 1),
                new(1,"Biomass", 1),
                new(1,"Steel Ingot", 3),
                new(1,"Plastic", 5),
                new(1,"Rubber", 5),
                new(1,"Caterium Ingot", 6),
                new(1,"Alumina Solution", 7),
                new(1,"Quartz Crystal", 7),
                new(1,"Silica", 7),
                new(1,"Sulfuric Acid", 7),
                new(2,"Iron Plate", 1),
                new(2,"Iron Rod", 1),
                new(2,"Wire", 1),
                new(2,"Cable", 1),
                new(2,"Screw", 1),
                new(2,"Copper Sheet", 2),
                new(2,"Solid Biofuel", 2),
                new(2,"Steel Pipe", 3),
                new(2,"Steel Beam", 3),
                new(2,"Heavy Oil Residue", 5),
                new(2,"Quickwire", 6),
                new(2,"Aluminum Scrap", 7),
                new(2,"Encased Uranium Cell", 8),
                new(2,"Copper Powder", 8),
                new(3,"Reinforced Iron Plate", 1),
                new(3,"Rotor", 2),
                new(3,"Encased Industrial Beam", 4),
                new(3,"Stator", 4),
                new(3,"Fuel", 5),
                new(3,"Petroleum Coke", 5),
                new(3,"Circuit Board", 5),
                new(3,"Aluminum Ingot", 7),
                new(3,"AI Limiter", 7),
                new(3,"Nitric Acid", 8),
                new(4,"Smart Plating", 2),
                new(4,"Modular Frame", 2),
                new(4,"Automated Wiring", 4),
                new(4,"Motor", 4),
                new(4,"Computer", 5),
                new(4,"High Speed Connector", 6),
                new(4,"Alclad Aluminum Sheet", 7),
                new(4,"Aluminum Casing", 7),
                new(4,"Crystal Oscillator", 7),
                new(4,"Electromagnetic Control Rod", 8),
                new(5,"Versatile Framework", 3),
                new(5,"Heavy Modular Frame", 4),
                new(5,"Modular Engine", 5),
                new(5,"Battery", 7),
                new(5,"Radio Control Unit", 7),
                new(5,"Supercomputer", 7),
                new(5,"Uranium Fuel Rod", 8),
                new(5,"Heat Sink", 8),
                new(6,"Adaptive Control Unit", 5),
                new(6,"Magnetic Field Generator", 8),
                new(6,"Cooling System", 8),
                new(6,"Fused Modular Frame", 8),
                new(6,"Uranium Waste", 8),
                new(6,"Nuclear Power Generation", 8),
                new(7,"Assembly Director System", 7),
                new(7,"Turbo Motor", 8),
                new(7,"Nonfissile Uranium", 8),
                new(7,"Pressure Conversion Cube", 8),
                new(8,"Thermal Propulsion Rocket", 8),
                new(8,"Plutonium Pellet", 8),
                new(8,"Nuclear Pasta", 8),
                new(9,"Encased Plutonium Cell", 8),
                new(10,"Plutonium Fuel Rod", 8),
                new(11,"Plutonium Waste", 8),
            };

            ItemGroups = itemGroups;

        }
    }
}
